#!/bin/bash

validateNums(){
 validChars="$(echo $1 | sed -e 's/[^0-9]//g')"
 [[ -z "$1" ]] && echo "Please enter an argument!" 

    if [[ "$validChars" = "$1" ]]; then
      echo "VALID: $validChars"
      #return 0
    else
      echo "Invalid"
      #return 1
    fi
}

validateAlphaNumeric(){
 [[ -z "$1" ]] && echo "Please enter an argument!" 
 validChars="$(sed -e 's/[^[:alnum:]]//g'<<< "$1")"
    if [[ "$validChars" = "$1" ]]; then
      echo "VALID: $validChars"
      #return 0
    else
      echo "Invalid"
      #return 1
    fi
  }

validateExercise(){
  [[ -z "$1" ]] && echo "Please enter an argument!" 
  searchExercise=$(grep -i "${exercise}" exerciseLibBasic)
  case "${searchExercise,,}" in
    "")
        echo "No exercises listed as $exercise"
        read -p "Would you like to add an exercise?" addExerciseInput
        if [[ "${addExerciseInput,,}" == 'yes' ]]; then
          addExercise
        else
          echo 'not adding that exercise'
        fi

        echo "find out how to remove accidents"
        ;;
      *)
        echo "Exercise found in library!"
        ;;
    esac
}
