#!/bin/bash

source /home/chuck/programming/repos/Bash-Fitness-Tracker/attempt2Functions
maxSQT=470; SQT11=
maxBN=315
maxDL=565


variableMaker2 SQT



echo "
+=============================================================================================+
|Cycle $c | sets x reps | Monday | Tuesday | Wednesday | Thursday | Friday | Saturday | Sunday |
|========+=============+========+=========+===========+==========+========+===================|
|Week  1 |  1   x  5   | "   $SQT111    "| Cardio  |  $BN111   |  Cardio  | $DL111 | Back Day | Chest  |
|        |  1   x  5   | $SQT112| Cardio  |  $BN112   |  Cardio  | $DL112 | Back Day | Chest  |
|        |  1   x  5+  | $SQT113| Cardio  |  $BN113   |  Cardio  | $DL113 | Back Day | Chest  |
| Acc    |  4   x  10  | $DLACC | Cardio  |   $ROW    |  Cardio  | $SQACC | Back Day | Chest  |
|========+=============+========+=========+===========+==========+========+===================|
|Week  2 |  1   x  3   | $SQT121| Cardio  |   $BN21   |  Cardio  | $DL21  | Back Day | Chest  |
|        |  1   x  3   | $SQT122| Cardio  |   $BN22   |  Cardio  | $DL22  | Back Day | Chest  |
|        |  1   x  3+  | $SQT123| Cardio  |   $BN23   |  Cardio  | $DL23  | Back Day | Chest  |
| Acc    |  4   x  10  | $DLACC | Cardio  |   $ROW    |  Cardio  | $SQACC | Back Day | Chest  |
|========+=============+========+=========+===========+==========+========+===================|
|Week  3 |  1   x  5   | $SQT131| Cardio  |   $BN31   |  Cardio  | $DL31  | Back Day | Chest  |
|        |  1   x  3   | $SQT132| Cardio  |   $BN32   |  Cardio  | $DL32  | Back Day | Chest  |
|        |  1   x  1+  | $SQT133| Cardio  |   $BN33   |  Cardio  | $DL33  | Back Day | Chest  |
| Acc    |  4   x  10  | $DLACC | Cardio  |   $ROW    |  Cardio  | $SQACC | Back Day | Chest  |
|========+=============+========+=========+===========+==========+========+==========+========+
|Week  4 |  4   x  10  | $SQDL4 | Cardio  |   $BNDL4  |  Cardio  | $DLDL4 | Back Day | Chest  |
| Acc    |  4   x  10  | $DLACC | Cardio  |   $ROW    |  Cardio  | $SQACC | Back Day | Chest  |
|========+=============+========+=========+===========+==========+========+==========+========+
"
