#!/bin/bash
roundingTest(){
  maxValue=$1
  percentage=$2
  weight=$(echo "scale=0; (($maxValue * $percentage + 4)/5)*5" | bc)
  echo $weight 

 #if (( result == 0 ))
   # result="$result"
    
  #fi

}

variableMaker2() {
  ex="$1"
  i=1
  echo "How many cycles do you want to complete?"
  read cycles
    #var names should indicate exerscise,cycle,week,set SQT123 Squat cycle1 week2 set3
    #var dec; conditions; add to var
  for (( c=1; c<=cycles; c++ )); do
    for (( w=1; w<=3; w++ )); do       
      for (( s=1; s<=3; s++, i++ )); do     
        var="${ex}${c}${w}${s}"
        declare -g "$var=$((360 + $i))"
        #echo "...${!var}..."
      done
    done
  done
}

