#!/bin/bash

i=0

#while [[ i -lt 5 ]]; do
#  data{$i}="data$i"
#  echo $data{$i}
#done
i=0
e=2

whil [[ $i -lt 5 ]]; do
  data[$i]="data$i and $e"
  echo "${data[$i]}"
  ((i++))
  ((e++))
done

main_entry="${data[1]} ${data[2]}"
echo "$main_entry"
