#!/bin/bash

mainScreen(){
  
local userInput
  echo "What would you like to do?
  Log Workout
  Get Summary
  GetRoutine"

read -r userInput
  case "${userInput}" in
    'log workout')
      exerciseLoggerV2
      ;;
    'Get Summary')
      echo "get a summary of a routine"
      ;;
    'get routine')
      echo "Get a routine from a lib"
      ;;
    'exit')
      exit
      ;;
    *)
      echo "Choice not recognized"
      mainScreen
      ;;
    esac


}

validateExercise(){
  searchExercise=$(grep -i "${exercise}" exerciseLibBasic)
  case "${searchExercise,,}" in
    "")
        echo "No exercises listed as $exercise"
        read -p "Would you like to add an exercise?" addExerciseInput
        if [[ "${addExerciseInput,,}" == 'yes' ]]; then
          addExercise
        else
          echo 'not adding that exercise'
        fi

        echo "find out how to remove accidents"
        ;;
      *)
        echo "Exercise found in library!"
        ;;
    esac
}

addExercise(){
  local userExercise
	echo "Please enter the exercise you want to add"
	read -r userExercise
	echo "Enter the type of exercise:
        Compound
        Accesory
        Cardio"
  read -r exerciseTpye
  echo "What is the focus of the exercise?
          Upper
          Lower"
  read -r exerciseFocus
  echo "What is the major muscle group?
        Full-body
        Chest
        Back
        Quads
        Hamstrings
        Shoulders
        Triceps
        Biceps
        Core"
  read -r exerciseMuscleGroup

}

removeExercise(){
  echo "remove exercises from lib"
}

exerciseLoggerV2(){
  local numExercise i date exercises entry
  local exercise weight sets reps
  read -p "How many exercises did you perform? " numExercises
  i=1
  date="$(date "+%A %B %D")"

  exercises=()
  while [[ "$i" -le "$numExercises" ]]; do 
      read -p "Please enter your exercise: " exercise
      validateExercise
      read -p "Please enter your weight: " weight
      read -p "Please enter your sets: " sets
      read -p "Please enter your reps: " reps
      exercises+=("{\"exercise-$i\": \"$exercise\", \"weight\": $weight, \"sets\": $sets, \"reps\": $reps}")
    ((i++))
  done

  entry=$(IFS=,; echo "${exercises[*]}")

  echo "{\"date\": \"$date\", \"exercises\": [ $entry] }" >>exerciselog.json
}
