#!/bin/bash

### Screens ###

mainScreen(){
local userInput
  echo "What would you like to do?
  Log Workout
  Get Summary
  GetRoutine"

read -r userInput
  case "${userInput,,}" in
    'log workout')
      exerciseLogger
      ;;
    'get summary')
      echo "get a summary of a routine"
      ;;
    'get routine')
      echo "Get a routine from a lib"
      ;;
    'exit')
      exit
      ;;
    *)
      echo "Choice not recognized"
      mainScreen
      ;;
    esac


}


### SCREEN FUNCTIONS ###

create_profile(){
 echo "Please select an option
  Create profile
  Load profile
  List options
 "
 read -r $userInput
  

 read -p "What is your name?" userName
 #validate user name
}


exerciseLogger(){
  local numExercise i date exercises entry
  local exercise weight sets reps
  read -p "How many exercises did you perform? " numExercises
  i=1
  date="$(date "+%A %B %D")"

  exercises=()
  while [[ "$i" -le "$numExercises" ]]; do 
      read -p "Please enter your exercise: " exercise
      #check for only letters
#      validateExercise
      read -p "Please enter your weight: " weight
      read -p "Please enter your sets: " sets
      read -p "Please enter your reps: " reps
      exercises+=("{\"exercise-$i\": \"$exercise\", \"weight\": $weight, \"sets\": $sets, \"reps\": $reps}")
    ((i++))
  done

  entry=$(IFS=,; echo "${exercises[*]}")

  echo "{\"date\": \"$date\", \"exercises\": [ $entry] }" >>exerciselog.json
}


validateUsername(){
 echo "I will check if a username exists"
}

getSummary(){
 echo "I need to finish create profile"  
}

addExercise(){
  echo "Should add exercises to lib"
}

removeExercise(){
  echo "remove exercises from lib"
}

mainScreen
